# Generated by Django 2.2 on 2019-04-15 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gambario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del gambario', max_length=10)),
                ('habitantes', models.CharField(help_text='Habitantes del gambario', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gambario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='temperature.Gambario')),
            ],
        ),
    ]
